name: BatteryMonitor
options:
  bundleIdPrefix: com.batterymonitor
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: false

targets:
  BatteryMonitor:
    type: application
    platform: macOS
    sources:
      - path: Sources/BatteryMonitor
        excludes:
          - main_cli.swift
    resources:
      - path: SupportFiles/Assets.xcassets
    info:
      path: SupportFiles/Info.plist
      properties:
        LSUIElement: true
        NSPrincipalClass: NSApplication
    entitlements:
      path: SupportFiles/BatteryMonitor.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.swacktools.batterymonitor
        MARKETING_VERSION: "1.0.4"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: WHS8S6ZW43
        OTHER_SWIFT_FLAGS: "-parse-as-library"
        INFOPLIST_FILE: SupportFiles/Info.plist
        CODE_SIGN_ENTITLEMENTS: SupportFiles/BatteryMonitor.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies: []
